JECT>

  <Field name="dataTypeD" value="1"></Field>

  <Field name="dataDisplayTypeD" value="0"></Field>

  <Field name="userNameD" value=""></Field>

  <Field name="siteNameD" value=""></Field>

  <Field name="gwNameD" value=""></Field>

  <Field name="gwIPD" value=""></Field>

  <Field name="severityLevelD" value="1"></Field>

  <Field name="dataD" value="Service was started"></Field>

  <Field name="helpdeskRecordTypeD" value="-1"></Field>

</OBJECT>

[ 2256 8248][17 Oct 18:42:48][DIAGNOSTIC] [COVERAGE] [Diagnostic_eventLogHandler::Diagnostic_eventLogHandler::writeEventToLog(s)] __start__
[ 2256 8248][17 Oct 18:42:48][DIAGNOSTIC] [COVERAGE] [Diagnostic_eventLogHandler::Diagnostic_eventLogHandler::writeEventToLog(s)] __end__ Total: 0 milliseconds.
[ 2256 8248][17 Oct 18:42:48][TR_CONN_MANAGER] diagnostic_reporter: entering...
[ 2256 8248][17 Oct 18:42:48][TR_CONN_MANAGER] TR_CONN_MANAGER::CreateAndSendNotification: TrEventManager is not ready yet - ignore this notification - return
[ 2256 8248][17 Oct 18:42:48][DIAGNOSTIC] [COVERAGE] [Diagnostic_EventReporter::_report_event(s)] __end__ Total: 1 milliseconds.
[ 2256 8248][17 Oct 18:42:48][DIAGNOSTIC] [COVERAGE] [Diagnostic_EventReporter::report_helpdesk_event_1(s)] __end__ Total: 1 milliseconds.
[ 2256 8248][17 Oct 18:42:48][TracService] Software\CheckPoint\TRAC\5.0 exists - no need to backup
[ 2256 8248][17 Oct 18:42:48][CONFIG_MANAGER] ConfigurationManager::create: __start__ 18:42:48.173
[ 2256 8248][17 Oct 18:42:48][CONFIG_MANAGER] ConfigurationManager::ConfigurationManager: __start__ 18:42:48.173
[ 2256 8248][17 Oct 18:42:48][CONFIG_MANAGER] ConfigurationManager::init(): __start__ 18:42:48.173
[ 2256 8248][17 Oct 18:42:48][CONFIG_MANAGER] ConfigurationManager::load(): __start__ 18:42:48.173
[ 2256 8248][17 Oct 18:42:48][CONFIG_MANAGER] ConfigurationManager::loadDefaultParams()
[ 2256 8248][17 Oct 18:42:48][FileManager] FileManager::openFile: file "trac.defaults" does not exist
[ 2256 8248][17 Oct 18:42:48][FileManager] FileManager::readFile: error occured while opening the file "trac.defaults"
[ 2256 8248][17 Oct 18:42:48][CONFIG_MANAGER] ConfigurationManager::loadDefaultParams() error reading trac.defaults file in ConfigurationManager::loadDefaultParams()
[ 2256 8248][17 Oct 18:42:48][RaisException] RaisException::BaseException::BaseException: error code = 11, error message = error reading file in ConfigurationManager::loadDefaultParams(), file name =ConfigurationManager.cpp, line number = 1369
[ 2256 8248][17 Oct 18:42:48][CONFIG_MANAGER] ConfigurationManager::load(): __end__ 18:42:48.174. Total time - 1 milliseconds
[ 2256 8248][17 Oct 18:42:48][CONFIG_MANAGER] ConfigurationManager::init(): __end__ 18:42:48.174. Total time - 1 milliseconds
[ 2256 8248][17 Oct 18:42:48][CONFIG_MANAGER] ConfigurationManager::ConfigurationManager: __end__ 18:42:48.174. Total time - 1 milliseconds
[ 2256 8248][17 Oct 18:42:48][CONFIG_MANAGER] ConfigurationManager::create: __end__ 18:42:48.174. Total time - 1 milliseconds
[ 2256 8248][17 Oct 18:42:48][DIAGNOSTIC] [COVERAGE] [Diagnostic_EventReporter::report_helpdesk_event_1(s)] __start__
[ 2256 8248][17 Oct 18:42:48][DIAGNOSTIC] [DEBUG] [Diagnostic_EventReporter::report_helpdesk_event_1(s)]  eventDisplayType: 4 severityLevel: 1 userName:  siteName:  gwName:  gwIP:  eventText: Error in client initialization
[ 2256 8248][17 Oct 18:42:48][DIAGNOSTIC] [COVERAGE] [Diagnostic_Id_Generator::generateId(s)] __start__
[ 2256 8248][17 Oct 18:42:48][DIAGNOSTIC] [INFO] [Diagnostic_Id_Generator::generateId(s)] new id is: timeStamp: 1666050168, serialNumWithinTheSecond: 1
[ 2256 8248][17 Oct 18:42:48][DIAGNOSTIC] [COVERAGE] [Diagnostic_Id_Generator::generateId(s)] __end__ Total: 0 milliseconds.
[ 2256 8248][17 Oct 18:42:48][DIAGNOSTIC] [COVERAGE] [Diagnostic_EventReporter::_report_event(s)] __start__
[ 2256 8248][17 Oct 18:42:48][XmlWrapper] XmlDocument::XmlDocument: inside
[ 2256 8248][17 Oct 18:42:48][XmlWrapper] XmlDocument::SaveString: inside
[ 2256 8248][17 Oct 18:42:48][DIAGNOSTIC] [DEBUG] [Dia0:35][DIAGNOSTIC] [COVERAGE] [Diagnostic_eventLogHandler::Diagnostic_eventLogHandler::writeEventToLog(s)] __start__
[ 3296 4784][17 Oct 18:50:35][DIAGNOSTIC] [COVERAGE] [Diagnostic_eventLogHandler::Diagnostic_eventLogHandler::writeEventToLog(s)] __end__ Total: 0 milliseconds.
[ 3296 4784][17 Oct 18:50:35][TR_CONN_MANAGER] diagnostic_reporter: entering...
[ 3296 4784][17 Oct 18:50:35][TR_CONN_MANAGER] TR_CONN_MANAGER::CreateAndSendNotification: TrEventManager is not ready yet - ignore this notification - return
[ 3296 4784][17 Oct 18:50:35][DIAGNOSTIC] [COVERAGE] [Diagnostic_EventReporter::_report_event(s)] __end__ Total: 2 milliseconds.
[ 3296 4784][17 Oct 18:50:35][DIAGNOSTIC] [COVERAGE] [Diagnostic_EventReporter::report_helpdesk_event_1(s)] __end__ Total: 3 milliseconds.
[ 3296 4784][17 Oct 18:50:35][TracService] Software\CheckPoint\TRAC\5.0 exists - no need to backup
[ 3296 4784][17 Oct 18:50:35][CONFIG_MANAGER] ConfigurationManager::create: __start__ 18:50:35.224
[ 3296 4784][17 Oct 18:50:35][CONFIG_MANAGER] ConfigurationManager::ConfigurationManager: __start__ 18:50:35.224
[ 3296 4784][17 Oct 18:50:35][CONFIG_MANAGER] ConfigurationManager::init(): __start__ 18:50:35.224
[ 3296 4784][17 Oct 18:50:35][CONFIG_MANAGER] ConfigurationManager::load(): __start__ 18:50:35.224
[ 3296 4784][17 Oct 18:50:35][CONFIG_MANAGER] ConfigurationManager::loadDefaultParams()
[ 3296 4784][17 Oct 18:50:35][FileManager] FileManager::openFile: file "trac.defaults" does not exist
[ 3296 4784][17 Oct 18:50:35][FileManager] FileManager::readFile: error occured while opening the file "trac.defaults"
[ 3296 4784][17 Oct 18:50:35][CONFIG_MANAGER] ConfigurationManager::loadDefaultParams() error reading trac.defaults file in ConfigurationManager::loadDefaultParams()
[ 3296 4784][17 Oct 18:50:35][RaisException] RaisException::BaseException::BaseException: error code = 11, error message = error reading file in ConfigurationManager::loadDefaultParams(), file name =ConfigurationManager.cpp, line number = 1369
[ 3296 4784][17 Oct 18:50:35][CONFIG_MANAGER] ConfigurationManager::load(): __end__ 18:50:35.224. Total time - 0 milliseconds
[ 3296 4784][17 Oct 18:50:35][CONFIG_MANAGER] ConfigurationManager::init(): __end__ 18:50:35.224. Total time - 0 milliseconds
[ 3296 4784][17 Oct 18:50:35][CONFIG_MANAGER] ConfigurationManager::ConfigurationManager: __end__ 18:50:35.224. Total time - 0 milliseconds
[ 3296 4784][17 Oct 18:50:35][CONFIG_MANAGER] ConfigurationManager::create: __end__ 18:50:35.224. Total time - 0 milliseconds
[ 3296 4784][17 Oct 18:50:35][DIAGNOSTIC] [COVERAGE] [Diagnostic_EventReporter::report_helpdesk_event_1(s)] __start__
[ 3296 4784][17 Oct 18:50:35][DIAGNOSTIC] [DEBUG] [Diagnostic_EventReporter::report_helpdesk_event_1(s)]  eventDisplayType: 4 severityLevel: 1 userName:  siteName:  gwName:  gwIP:  eventText: Error in client initialization
[ 3296 4784][17 Oct 18:50:35][DIAGNOSTIC] [COVERAGE] [Diagnostic_Id_Generator::generateId(s)] __start__
[ 3296 4784][17 Oct 18:50:35][DIAGNOSTIC] [INFO] [Diagnostic_Id_Generator::generateId(s)] new id is: timeStamp: 1666050635, serialNumWithinTheSecond: 1
[ 3296 4784][17 Oct 18:50:35][DIAGNOSTIC] [COVERAGE] [Diagnostic_Id_Generator::generateId(s)] __end__ Total: 0 milliseconds.
[ 3296 4784][17 Oct 18:50:35][DIAGNOSTIC] [COVERAGE] [Diagnostic_EventReporter::_report_event(s)] __start__
[ 3296 4784][17 Oct 18:50:35][XmlWrapper] XmlDocument::XmlDocument: inside
[ 3296 4784][17 Oct 18:50:35][XmlWrapper] XmlDocument::SaveString: inside
[ 3296 4784][17 Oct 18:50:35][DIAGNOSTIC] [DEBUG] [Diagnostic_EventReporter::_report_event(s)] new event after removing 0d0a: 

<OBJECT name="helpdesk event" type="DiagnosticHelpdeskEventData">

  <OBJECT name="idD" type="Diagnostic_RecordId">
    <Field name="timeStampD" value="1666050635"></Field>
    <Field name="serialD" value="1"></Field>
  </OBJECT>

  <Field name="dataTypeD" value="1"></Field>

  <Field name="dataDisplayTypeD" value="4"></Field>

  <Field name="userNameD" value=""></Field>

  <Field name="siteNameD" value=""></Field>

  <Field name="gwNameD" value=""></Field>

  <Field name="gwIPD" value=""></Field>

  <Field name="severityLevelD" value="1"></Field>

  <Field name="dataD" value="Error in client initialization"></Field>

  <Field name="helpdeskRecordTypeD" value="-1"></Field>

</OBJECT>

[ 3296 4784][17 Oct 18:50:35][DIAGNOSTIC] [COVERAGE] [Diagnostic_eventLogHandler::Diagnostic_eventLogHandler::writeEventToLog(s)] __start__
[ 3296 4784][17 Oct 18:50:35][DIAGNOSTIC] [COVERAGE] [Diagnostic_eventLogHandler::Diagnostic_eventLogHandler::writeEventToLog(s)] __end__ Total: 0 milliseconds.
[ 3296 4784][17 Oct 18:50:35][TR_CONN_MANAGER] diagnostic_reporter: entering...
[ 3296 4784][17 Oct 18:50:35][TR_CONN_MANAGER] TR_CONN_MANAGER::CreateAndSendNotification: TrEventManager is not ready yet - ignore this notification - return
[ 3296 4784][17 Oct 18:50:35][DIAGNOSTIC] [COVERAGE] [Diagnostic_EventReporter::_report_event(s)] __end__ Total: 1 milliseconds.
[ 3296 4784][17 Oct 18:50:35][DIAGNOSTIC] [COVERAGE] [Diagnostic_EventReporter::report_helpdesk_event_1(s)] __end__ Total: 2 milliseconds.
[ 3296 4784][17 Oct 18:50:35][TR_OVERSITE] TR_OVERSITE::Create: EXCEPTION!
[ 3296 4784][17 Oct 18:50:35][TR_OVERSITE] TR_OVERSITE::Create: error reading file in ConfigurationManager::loadDefaultParams()
[ 3296 4784][17 Oct 18:50:35][TracService] ServiceMain: mainloop exited without stopping the service, calling exit
[ 3296 4784][17 Oct 18:50:35][] COM_Initializer::Dtor: nothing to do
[ 3296 4784][17 Oct 18:50:35][proxy_API] ~OS_API
[ 3296 4784][17 Oct 18:50:35][Multi-site] [COVERAGE] [MultiSiteAutoUpdateManager::~MultiSiteAutoUpdateManager] __start__
[ 3296 4784][17 Oct 18:50:35][Multi-site] [COVERAGE] [MultiSiteAutoUpdateManager::reset] __start__
[ 3296 4784][17 Oct 18:50:35][Multi-site] [COVERAGE] [MultiSiteAutoUpdateManager::setAutoUpdateState] __start__
[ 3296 4784][17 Oct 18:50:35][Multi-site] [INFO] [MultiSiteAutoUpdateManager::setAutoUpdateState]  moving form state eAutoUpdateState_preInit to state eAutoUpdateState_preInit
[ 3296 4784][17 Oct 18:50:35][Multi-site] [COVERAGE] [MultiSiteAutoUpdateManager::setAutoUpdateState] __end__ Total: 0 milliseconds.
[ 3296 4784][17 Oct 18:50:35][Multi-site] [COVERAGE] [MultiSiteAutoUpdateManager::reset] __end__ Total: 0 milliseconds.
[ 3296 4784][17 Oct 18:50:35][Multi-site] [COVERAGE] [MultiSiteAutoUpdateManager::~MultiSiteAutoUpdateManager] __end__ Total: 0 milliseconds.
[ 3296 4784][17 Oct 18:50:35][Multi-site] [COVERAGE] [MultiSiteEncDomainMapper::~MultiSiteEncDomainMapper] __start__
[ 3296 4784][17 Oct 18:50:35][Multi-site] [COVERAGE] [MultiSiteEncDomainMapper::~MultiSiteEncDomainMapper] __end__ Total: 0 milliseconds.
[ 948 12124][17 Oct 18:50:35][TracService] ServiceMain: Entered service's main entry point (Check Point Endpoint Security)
[ 948 12124][17 Oct 18:50:35][cpservice] service_report_status_to_scm: Reporting start pending
[ 948 12124][17 Oct 18:50:35][TracService] IsDisabledInEps: failed to rea